gitapi/appone/urls.py
from django.conf.urls import url

from appone import views

app_name = 'basic'

urlpatterns = [
    #url(r'^gitdata/$', views.home, name='home'),
    url(r'^more/$', views.more_info,name="more_info"),
    url(r'stack/$',views.stackoverflow,name="stackoverflow"),
]

gitapi/gitapi/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from appone import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index, name='index'),
    url(r'^', include('appone.urls')),
]

gitapi/appone/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class DevProfile(models.Model):
    name = models.CharField(max_length=100)

gitapi/appone/forms.py
from django import forms

from django.db import models

#forms without db associated

class FormName(forms.Form):
    # placeholder = 'Git Username'
    name = forms.CharField(initial='Git Username', required=True)


class FormStackOverflow(forms.Form):
    id = forms.CharField(initial='StackOverflow id', required=True)

gitapi/appone/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
import requests
import feedparser
#import the app forms
from appone import forms
from appone.models import DevProfile


def index(request):
    """view loads index template after form is valid loads git info"""
    # forms usage
    form = forms.FormName()
    if request.method == 'POST':
        form = forms.FormName(request.POST)
        print (form.errors)
        if form.is_valid():
            #manually create object in models
            obj = DevProfile()
            # take the user name from form
            user_name = form.cleaned_data['name']
            #save the object in db
            obj.name = user_name
            obj.save()
            response = requests.get('https://api.github.com/users/' + user_name)
            try:
                user_data = response.json()
            except:
                #no json object could be decoded
                return render(request, 'appone/index.html')
            return render(request, 'appone/gitinfo.html', {
                'location': user_data['location'],
                'bio': user_data['bio'],
                'no_of_repos': user_data['public_repos'],
                'git_member_since': user_data['created_at'],
                'followers': user_data['followers'],
                'following': user_data['following'],
                'git_user_name':user_data['login'],
            })
        #form is invalid
        return render(request,'appone/index.html')
    #the first thing that is returned
    return render(request,'appone/index.html',{'form':form})


def more_info(request):
    """read object from db and call api"""
    query_set = DevProfile.objects.all()
    #thake the last element from the db
    last_value_added = str(query_set[len(query_set)-1].name)
    #print (last_value_added)
    """view for API calls"""
    response = requests.get('https://api.github.com/users/'+last_value_added+'/repos')
    repo_data = response.json()
    return render(request, 'appone/more.html', {
                'all_data':repo_data,
                })

def stackoverflow(request):
    """get RSS feed based on user ID"""
    form = forms.FormStackOverflow()
    if request.method == 'POST':
        form = forms.FormStackOverflow(request.POST)
        if form.is_valid():
            user_id = form.cleaned_data['id']
            #get RSS feed 7013263
            data =feedparser.parse('https://stackoverflow.com/feeds/user/'+user_id)
            #data dict
            data_dict = data.feed
            return render(request,'appone/stack.html',{'dictionar':data_dict.values()})
    return render(request,'appone/stack.html',{'form':form})

gitapi/templates/appone/gitinfo.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <meta charset="UTF-8">
    <title>User Info</title>
</head>
<body>
<div class="container">
<h2>Developer Profile</h2>
<a href="{% url 'index' %}">Home</a>
<a href="{% url 'basic:more_info' %}">More Info</a>
<ul>
    <li> <strong>Location</strong>: {{location}}</li>
    <li><strong>Joined GIT:</strong>{{git_member_since}}</li>
    <li><strong>Number of repos</strong>: {{no_of_repos}}</li>
    <li> <strong>About:</strong>: {{bio}}</li>
    <li> <strong>Followers</strong>: {{followers}}</li>
    <li> <strong>Following</strong>: {{following}}</li>

</ul>

</div>
</body>
</html>

gitapi/templates/appone/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <meta charset="UTF-8">
    <title>HomePage</title>
</head>
<body>
<div class="container">
    <a href="{% url 'index' %}">Home</a>
    <a href="{% url 'basic:stackoverflow' %}">Stack reputation</a>
    <h1> Home page </h1>
    <br>
    <form method="post" action="#">
    <!--Form as paragraph-->
        {% csrf_token %}
        {{form.as_p}}
        <!--submit button as btn-primary class bootstrap-->
        <input type="submit" class="btn btn-primary" value="Get Data">
    </form>
    <hr>
<div>
</body>
</html>

gitapi/templates/appone/more.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>More info</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

</head>
<body>
<div class="container">
        <a href="{% url 'index' %}">Home</a>
        <h1>Developer projects and programming languages</h1>
        <br>
        <hr>
    <!--render the dict from more_info view-->
    {% for i in all_data %}
            <li> {{i.name}} in <strong>{{i.language}}</strong>
                <br>
                Available info about project: {{i.description}}
            </li>

    {% endfor %}


</div>
</body>
</html>

gitapi/templates/appone/stack.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <title>StackOverflow</title>
</head>
<body>
<div class="container">
     <a href="{% url 'index' %}">Home</a>
<form method="POST" action="#">
        {% csrf_token %}
        {{form.as_p}}

        <!--submit button as btn-primary class bootstrap-->
        <input type="submit" class="btn btn-primary" value="Get RSS feed">
    </form>
<hr>
    {% for i in dictionar %}
        <!--<li>{{i.title}}</li>-->
        <!--<li>{{i.id}}</li>-->
        <!--<li>{{i.subtitle}}</li>-->
        <li>{{i}}</li>
    {% endfor %}

</div>
</body>
</html>